# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

<<<<<<< HEAD
[[main]]
  name = "About"
  url = "#about"
  weight = 10

[[main]]
  name = "Open Case Studies"
  url = "#ocs"
  weight = 20

[[main]]
  name = "OCS Table Search"
  url = "#DTtable"
  weight = 30


#[[main]]
#  name = "Data Science search"
#  url = "#projects"
#  weight = 35

#[[main]]
#  name = "Stats search"
#  url = "#statsprojects"
#  weight = 36

[[main]]
  name = "OCS search"
  url = "#contextprojects"
  weight = 37
=======
# # Align the main menu to the right of the page? (true/false)
# align_right = true

[[main]]
  name = "Home"
  url = "#about"
  weight = 1
>>>>>>> 4a04b86153c28cd6e8ae21ca588419539ece42e4

[[main]]
  name = "Blog"
  url = "#posts"
<<<<<<< HEAD
  weight = 40


[[main]]
  name = "Team"
  url = "#team"
  weight = 50

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 55
=======
  weight = 2

[[main]]
  name = "People"
  url = "#people"
  weight = 3

# [[main]]
#   name = "Tags"
#   url = "#tags"
#   weight = 5

[[main]]
  name = "Code of conduct"
  url = "#coc"
  weight = 4
>>>>>>> 4a04b86153c28cd6e8ae21ca588419539ece42e4

[[main]]
  name = "Contact"
  url = "#contact"
<<<<<<< HEAD
  weight = 60
=======
  weight = 5
>>>>>>> 4a04b86153c28cd6e8ae21ca588419539ece42e4

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
